# Generated by Django 5.1.14 on 2026-05-21 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0082_bot_guest_session_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botevent',
            name='event_sub_type',
            field=models.IntegerField(choices=[(1, 'Bot could not join meeting - Meeting Not Started - Waiting for Host'), (2, 'Fatal error - Process Terminated'), (3, 'Bot could not join meeting - Zoom Authorization Failed'), (4, 'Bot could not join meeting - Zoom Meeting Status Failed'), (5, 'Bot could not join meeting - Unpublished Zoom Apps cannot join external meetings. See https://developers.zoom.us/docs/distribute/sdk-feature-review-requirements/'), (6, 'Fatal error - RTMP Connection Failed'), (7, 'Bot could not join meeting - Zoom SDK Internal Error'), (8, 'Fatal error - UI Element Not Found'), (9, 'Bot could not join meeting - Request to join denied'), (10, 'Leave requested - User requested'), (11, 'Leave requested - Auto leave silence'), (12, 'Leave requested - Auto leave only participant in meeting'), (13, 'Fatal error - Heartbeat timeout'), (14, 'Bot could not join meeting - Meeting not found'), (15, 'Fatal error - Bot not launched'), (16, 'Bot could not join meeting - Waiting room timeout exceeded'), (17, 'Leave requested - Auto leave max uptime exceeded'), (18, 'Bot could not join meeting - Login required. Use signed in bots: https://docs.attendee.dev/guides/signed-in-bots to resolve.'), (19, 'Bot could not join meeting - Bot login attempt failed'), (20, 'Fatal error - Out of credits'), (21, 'Bot could not join meeting - Unable to connect to meeting. This usually means the meeting password in the URL is incorrect.'), (22, 'Fatal error - Boga (Meeting) Assistant internal error'), (23, 'Bot recording permission denied - Host denied permission'), (24, 'Bot recording permission denied - Request timed out'), (25, 'Bot recording permission denied - Host client cannot grant permission'), (26, 'Leave requested - Auto leave could not enable closed captions'), (27, 'Bot could not join meeting - Authorized user not in meeting timeout exceeded. See https://developers.zoom.us/blog/transition-to-obf-token-meetingsdk-apps/'), (28, 'Bot could not join meeting - Blocked by captcha (Verification challenge).')], null=True),
        ),
    ]
