services:
  attendee-worker-local:
    build: ./
    volumes:
     - .:/attendee
    networks:
      - attendee_network
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_URL=redis://redis:6379/5
      - DJANGO_SETTINGS_MODULE=attendee.settings.development
      - ENABLE_CHROME_SANDBOX=false
    command: "celery -A attendee worker -l INFO --concurrency=2"
    mem_limit: 1g
    cpus: 1.2
    shm_size: "1gb"

  attendee-scheduler-local:
    build: ./
    volumes:
     - .:/attendee
    networks:
      - attendee_network
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_URL=redis://redis:6379/5
      - DJANGO_SETTINGS_MODULE=attendee.settings.development
    command: "python manage.py run_scheduler"
    entrypoint: []
    mem_limit: 256m
    cpus: 0.3

  attendee-app-local:
    build: ./
    volumes:
     - .:/attendee
    networks:
      - attendee_network
    ports:
      - "8029:8000"
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_URL=redis://redis:6379/5
      - DJANGO_SETTINGS_MODULE=attendee.settings.development
      - USE_FORWARDED_HTTPS=true
      - CSRF_TRUSTED_ORIGINS=https://meeting-assistant.boga.co.id
    command: python manage.py runserver 0.0.0.0:8000
    entrypoint: []
    mem_limit: 512m
    cpus: 1.0

  attendee-webpage-streamer-local:
    build: ./
    volumes:
     - .:/attendee
    networks:
      - attendee_network
    ports:
      - "8029:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=attendee.settings.development
      - ENABLE_CHROME_SANDBOX=true
    command: "python bots/webpage_streamer/run_webpage_streamer.py"
    security_opt:
      - seccomp=./bots/web_bot_adapter/chrome_seccomp.json
    profiles:
      - webpage-streamer
    mem_limit: 2g
    cpus: 1.2

  postgres:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_DB: attendee_development
      POSTGRES_USER: attendee_development_user
      POSTGRES_PASSWORD: attendee_development_user
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    networks:
      - attendee_network
    restart: unless-stopped
    mem_limit: 1g
    cpus: 0.5

  redis:
    image: redis:7-alpine
    networks:
      - attendee_network
    restart: unless-stopped
    volumes:
      - redis:/data/redis
    mem_limit: 256m
    cpus: 0.3

networks:
  attendee_network:
    driver: bridge

volumes:
  postgres:
  redis: